apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-7mab
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-7mab
    app.kubernetes.io/part-of: ci10t-776-0016-app
  name: devfile-sample-7mab
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-7mab
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-7mab
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0016-tenant/ci10t-776-0016-app/devfile-sample-7mab@sha256:f8e2d54869044a1ce8350dce5b59293d6737fd4c721e301fbd3b3d4c57432f9e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
