apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-7mab
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0016-tenant/ci10t-776-0016-app/devfile-sample-7mab@sha256:f8e2d54869044a1ce8350dce5b59293d6737fd4c721e301fbd3b3d4c57432f9e
        name: my-nodejs
        resources: {}
status: {}
